### ISSUE TITLE
Prometheus alert rules

### ISSUE THREAD

**Issue by IduVlad** [c4po/harbor_exporter#66]
Would be nice to add prometheus alerts for metrics like:
```harbor_up```, ```harbor_system_volumes_bytes{storage="free"}```, ```harbor_health```, ```harbor_components_*```, ```go_memstats_frees_total```, ```harbor_image_vulnerability```

```
prometheusRule:
  labels:
    app: prometheus-operator
    release: prometheus-operator
  rules:
    - alert: HarborImageScanVulnerability
      expr: harbor_image_vulnerability > 3
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Harbor Image Scan Vulnerability Severity Critical
        summary: Image {{ "{{ $labels.image_name }}" }} has critical vulnerabilities
````
